9 commit

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -12,46 +12,27 @@ jobs:
     - name: Checkout código
       uses: actions/checkout@v3
       
-    - name: Configurar QEMU
-      uses: docker/setup-qemu-action@v2
-      
-    - name: Configurar Docker Buildx
-      uses: docker/setup-buildx-action@v2
-      
     - name: Iniciar sesión en Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         
-    - name: Construir y subir imágenes Docker
+    - name: Buscar docker-compose.yml
       run: |
-        # Lista de tus servicios
-        services=("list-services" "songs-service" "video-service")
+        echo "Buscando docker-compose.yml en todo el repositorio:"
+        find . -name docker-compose.yml
         
-        for service in "${services[@]}"
-        do
-          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest ./$service
-          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest
-        done
-
-    - name: Verificar estructura del directorio
-      run: |
-          echo "Contenido del directorio actual:"
-          ls -la
-          echo "Buscando docker-compose.yml:"
-          find . -name docker-compose.yml        
-
     - name: Construir y subir imagen de Docker Compose
       run: |
-        # Asumiendo que docker-compose.yml está en la raíz del repositorio
-        if [ -f "./docker-compose.yml" ]; then
-            docker-compose -f ./docker-compose.yml build
-            docker-compose -f ./docker-compose.yml push
+        COMPOSE_FILE=$(find . -name docker-compose.yml | head -n 1)
+        if [ -n "$COMPOSE_FILE" ]; then
+          echo "Archivo docker-compose.yml encontrado en: $COMPOSE_FILE"
+          docker-compose -f "$COMPOSE_FILE" build
+          docker-compose -f "$COMPOSE_FILE" push
         else
-            echo "Error: docker-compose.yml no encontrado en la ubicación esperada"
-            exit 1
+          echo "Error: docker-compose.yml no encontrado en el repositorio"
+          exit 1
         fi
-
     
         
